version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore: update github actions"
      prefix-development: "chore: update github actions"
